### ISSUE TITLE
Error when starting windowCli

### ISSUE THREAD

**Issue by SnehalataD** [hbutani/SQLWindowing#19]
I am using hive 0.7.1 with mysql as a metastore
I have copied com.sap.hadoop.windowing-0.0.1-SNAPSHOT.jar,com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar and groovy-all-1.8.0.jar files to /usr/lib/hive/lib folder.Also added windowing.sh file.Below is the content of this file :

THISSERVICE=windowingCli
export SERVICE_LIST="${SERVICE_LIST}${THISSERVICE} "

windowingCli () {
  CLASS=com.sap.hadoop.windowing.WindowingHiveCliDriver
  if $cygwin; then
    HIVE_LIB=`cygpath -w "$HIVE_LIB"`
  fi
  JAR=/usr/lib/hive/lib/com.sap.hadoop.windowing-0.0.1-SNAPSHOT.jar
  exec $HADOOP jar $JAR $CLASS "$@"
}

windowingCli_help () {
  windowingCli "--help"
}

Then I started metastore service with hive --service metastore command.

But hive --service windowingCli command does not work and it throws below exception.It seems jar files are corrupt.

[sb25634@hadoop02 ~]$ hive --service windowingCli -w /usr/lib/hive/lib/com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" java.io.IOException: Error opening job jar: /usr/lib/hive/lib/com.sap.hadoop.windowing-0.0.1-SNAPSHOT.jar
        at org.apache.hadoop.util.RunJar.main(RunJar.java:124)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:127)
        at java.util.jar.JarFile.<init>(JarFile.java:135)
        at java.util.jar.JarFile.<init>(JarFile.java:72)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:122)

What am I doing wrong?Am I using right jar files?Can you provide the above jar files?

**Comment by hbutani** [comment]
Can you rm the com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar from /usr/lib/hive/lib
directory; it is no more needed.

**Comment by SnehalataD** [comment]
The groovy-all-1.8.0.jar file that I was using was corrupt.After adding the new jar file.It started working.But now I have another problem.

I am now using com.sap.hadoop.windowing-0.0.2-SNAPSHOT.jar and groovy-all-1.8.0.jar.

[sb25634@hadoop02 ~]$ hive --service windowingCli
Hive history file=/tmp/sb25634/hive_job_log_sb25634_201208102242_482827921.txt
hive> wmode;
windowing mode is off
hive> wmode windowing;
hive> from transitiveClosure(<select * from Flights distribute by Dest> partition by Src,'Src','Dest') select Src,Dest
    > ;
BR.recoverFromMismatchedToken
BR.recoverFromMismatchedToken
com.sap.hadoop.windowing.WindowingException: line 1:83 mismatched input 'Src' expecting ID
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at com.sap.hadoop.windowing.runtime.WindowingShell.parse(WindowingShell.groovy:72)
        at com.sap.hadoop.windowing.runtime.WindowingShell.execute(WindowingShell.groovy:126)
        at com.sap.hadoop.windowing.runtime.WindowingShell$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.sap.hadoop.windowing.cli.WindowingClient3.executeQuery(WindowingClient3.groovy:28)
        at com.sap.hadoop.windowing.cli.WindowingClient3$executeQuery.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.processCmd(WindowingHiveCliDriver.groovy:117)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:286)
        at org.apache.hadoop.hive.cli.CliDriver$processLine.call(Unknown Source)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.main(WindowingHiveCliDriver.groovy:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Failed windowing query from transitiveClosure(<select * from Flights distribute by Dest> partition by Src,'Src','Dest') select Src,Dest
 line 1:83 mismatched input 'Src' expecting ID
hive> show tables;
BR.recoverFromMismatchedToken
BR.recoverFromMismatchedToken
com.sap.hadoop.windowing.WindowingException: line 1:0 mismatched input 'show' expecting FROM
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at com.sap.hadoop.windowing.runtime.WindowingShell.parse(WindowingShell.groovy:72)
        at com.sap.hadoop.windowing.runtime.WindowingShell.execute(WindowingShell.groovy:126)
        at com.sap.hadoop.windowing.runtime.WindowingShell$execute.call(Unknown Source)
        at com.sap.hadoop.windowing.cli.WindowingClient3.executeQuery(WindowingClient3.groovy:28)
        at com.sap.hadoop.windowing.cli.WindowingClient3$executeQuery.call(Unknown Source)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.processCmd(WindowingHiveCliDriver.groovy:117)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:286)
        at org.apache.hadoop.hive.cli.CliDriver$processLine.call(Unknown Source)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.main(WindowingHiveCliDriver.groovy:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Failed windowing query show tables line 1:0 mismatched input 'show' expecting FROM

Please help

**Comment by hbutani** [comment]
The transitiveClosure function is not yet available. Currently working on folding into Hive; hopefully will get to the Graph stuff in a couple of months.
