### ISSUE TITLE
Unknown partition column Symbol

### ISSUE THREAD

**Issue by aksgpt** [hbutani/SQLWindowing#23]
I am running the below on the table temp2 partitioned on Symbol and am continously getting the below error

hieve> from temp2 partition by Symbol order by Day with avg(Volume) over rows between unbounded preceding and current row as rollingavg select Symbol,Day,Rollingavg where <Day \\> 3> into path='/home/hive';
com.sap.hadoop.windowing.WindowingException: Unknown partition column Symbol
        at sun.reflect.GeneratedConstructorAccessor65.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at com.sap.hadoop.windowing.query.Translator.setupInputColumns(Translator.groovy:129)
        at com.sap.hadoop.windowing.query.Translator$setupInputColumns.callCurrent(Unknown Source)
        at com.sap.hadoop.windowing.query.Translator.setupQueryInput(Translator.groovy:97)
        at com.sap.hadoop.windowing.query.Translator$setupQueryInput.callCurrent(Unknown Source)
        at com.sap.hadoop.windowing.query.Translator.translate(Translator.groovy:48)
        at com.sap.hadoop.windowing.query.Translator$translate.call(Unknown Source)
        at com.sap.hadoop.windowing.runtime.WindowingShell.execute(WindowingShell.groovy:127)
        at com.sap.hadoop.windowing.runtime.WindowingShell$execute.call(Unknown Source)
        at com.sap.hadoop.windowing.cli.WindowingClient3.executeQuery(WindowingClient3.groovy:28)
        at com.sap.hadoop.windowing.cli.WindowingClient3$executeQuery.call(Unknown Source)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.processCmd(WindowingHiveCliDriver.groovy:117)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:403)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:338)
        at org.apache.hadoop.hive.cli.CliDriver$processLine.call(Unknown Source)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.main(WindowingHiveCliDriver.groovy:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:208)
## Failed windowing query from temp2 partition by Symbol order by Day with avg(Volume) over rows between unbounded preceding and current row as rollingavg select Symbol,Day,Rollingavg where <Day \\> 3> into path='/home/hive' Unknown partition column Symbol

The below Query gives the same error
from < select Day,SUM(Volume) as Volume,Symbol from temp2 GROUP BY Symbol,Day> partition by Symbol order by Day with avg(Volume) over rows between unbounded preceding and current row as rollingavg select Symbol,Day,Rollingavg where <Day \\> 3> into path='/home/hive'

**Comment by hbutani** [comment]
Hi,

Can you post the structure of the  temp2 table. 

regards,
Harish.

**Comment by aksgpt** [comment]
CREATE TABLE temp2 (Day STRING, Time STRING, Volume INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' PARTITIONED BY (Symbol STRING);

**Comment by aksgpt** [comment]
I got it working, Just replaced the Symbol to symbol in the windowing Query.Thanks anyways.

**Comment by hbutani** [comment]
ok thanks; but having to lowecase the column name is a bug; will follow up, but not in the master branch
