### ISSUE TITLE
No signature of method

### ISSUE THREAD

**Issue by aksgpt** [hbutani/SQLWindowing#24]
I am trying to start windowingCli but getting the below error on one of the cluster. It seems to be running fine with the other cluster.

 hive --service windowingCli
Hive history file=/tmp/root/hive_job_log_root_201210101710_1530752256.txt
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: jline.ConsoleReader.addCompletor() is applicable for argument types: ([Ljline.Completor;) values: [[org.apache.hadoop.hive.cli.CliDriver$5@78c08593, org.apache.hadoop.hive.cli.CliDriver$3@2781b3d4]]
Possible solutions: addCompletor(jline.Completor), getCompletors()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.main(WindowingHiveCliDriver.groovy:219)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:208)

here is my windowCli.sh file.

THISSERVICE=windowingCli
export SERVICE_LIST="${SERVICE_LIST}${THISSERVICE} "

windowingCli () {
  CLASS=com.sap.hadoop.windowing.WindowingHiveCliDriver
  if $cygwin; then
    HIVE_LIB=`cygpath -w "$HIVE_LIB"`
  fi
  JAR=${HIVE_LIB}/com.sap.hadoop.windowing-0.0.2-SNAPSHOT.jar
  exec $HADOOP jar $JAR $CLASS "$@"
}

windowingCli_help () {
  windowingCli "--help"
}

**Comment by hbutani** [comment]
which version of hive? Does vanilla Hive CLI work in this env?

**Comment by aksgpt** [comment]
Its throwing the error on hive version 0.9.0.I tested on version 0.8.1 and it worked fine.

**Comment by hbutani** [comment]
We have tested version 0.2 with hive-0.71 and hive-0.9. Currently working on the next version with hive-0.10, this has a similar issue with hive-CliDriver. I am guessing the change was made in hive-0.9.0.1. We hope to release the new version in a week to 10 days.

**Comment by shanchao** [comment]
Hi, i'm trying to use ur tools and face the same error. Is there anyway to bypass this as we're using CDH4.1.2 with hive-0.9.0+155， we don't want to downgrade hive for this.

$ hive --service windowingCli
Hive history file=/tmp/hdfs/hive_job_log_hdfs_201301301108_1115722583.txt
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/vipshop/platform/mapreduce/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/vipshop/platform/hive/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: jline.ConsoleReader.addCompletor() is applicable for argument types: ([Ljline.Completor;) values: [[org.apache.hadoop.hive.cli.CliDriver$5@7307f742, ...]]
Possible solutions: addCompletor(jline.Completor), getCompletors()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.sap.hadoop.windowing.WindowingHiveCliDriver.main(WindowingHiveCliDriver.groovy:254)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:208)

**Comment by hbutani** [comment]
We are no longer developing this. The hive-rt branch has the changes that would make it work with the version of hive you are looking at. But you will have to build from source.... We are now working to fold this functionality into Hive. If you are experimenting with this functionality, I would suggest using the patch from the 896 Jira: https://issues.apache.org/jira/browse/HIVE-896

**Comment by curlup** [comment]
@shanchao have you found solution for CDH4.1.2 with hive-0.9.0+155 ?

**Comment by hbutani** [comment]
Hi,

We don't actively support this library anymore. This functionality is in the process of being folded into hive. You can see the latest code at https://github.com/apache/hive, the ptf-windowing branch. Also checkout the Jiras in Hive Jira: look for Jiras whose Component is PTF-Windowing.

But if you want to try this with an older version of hive, I suggest you build from source. The jar in the downloads area is very old; it was not built for hive-0.9. 

regards,
Harish.

**Comment by conornash** [comment]
I am using HortonWorks HDP 1.2 and would like to use the SQL Windowing functions. I am getting the error mentioned at the start of this thread. However I am now confused due to the answers given in this thread - are the downloads from this project no longer compatible with Hive/Hadoop?

**Comment by hbutani** [comment]
The jar in the downloads area is quite old; was uploaded in August. Was tested against CDH3 and Hive 0.8
The source code in the hive-rt branch is more current and was tested against hive 0.9 and hive 0.10.

But since October we have stopped developing on this repo. This functionality was on top of hive and not part of hive. Since October we have working on folding this functionality into hive. The latest code is in the hive repo, ptf-windowing branch: https://github.com/apache/hive/tree/ptf-windowing

Moving forward you will just get this functionality in hive.  If you need to work with hive 0.9 (and possibly .10) you will have to build the code in the hive-rt branch in this repo.

Hope this helps.

**Comment by conornash** [comment]
Harish,

Thank you for the explanation - it certainly helps. Since I wish to get the windowing functions to work with Hive 0.10 it seems I should try to build this repo. However, I don't see any instructions for building. How do I build this repo?

Regarding the PTF-Windowing project within Hive, is this work functional yet? When do you expect windowing functions to be available in the main Hive distribution?

Thanks again.

**Comment by hbutani** [comment]
try mvn install -skipTests=true
If you are having build issues; I can email you the jar.

We try to keep the hive-ptf branch functional. Checkout ptf_general_queries.q; there are 69 example queries in it. The windowing support here is much closer to the SQL standard; also windowing/ptfs can now appear in subqueries, joins, views etc.  The best way to track progress is to look at the Jiras for the PTF-Windowing component.  And if you have requirements/opinions; eager to hear them...

**Comment by conornash** [comment]
Hi Harish,

I would like to install the latest version of Hive Windowing Functions. Since it has been a few months since we last spoke, where would you recommend I begin?

Thanks,

Conor

**Comment by xkm2000** [comment]
Hi Harish, 

I'm trying to build the jar from the latest source of hive-rt branch for hive 0.10.0 cdh4.2.1 ,
but failed after a couple of hours struggling with maven.

Unfortunately our hive environment can't update to 0.11.0 which support sql windowing.
Can you mail me(xkm2000@gmail.com) the jar file , 
or share the latest jar file in downloading area of this project. 

Thanks,

Rock

**Comment by shanchao** [comment]
I remembered that there was a discussion to merge this into cloudera version of hive, is there any progress of this?

This will a super huge step-up for us hive users :)

shanchao1

From: xkm2000
Date: 2013-05-30 09:18
To: hbutani/SQLWindowing
CC: shanchao
Subject: Re: [SQLWindowing] No signature of method (#24)
Hi Harish, 
I'm trying to build the jar from the latest source of hive-rt branch for hive 0.10.0 cdh4.2.1 , but failed after a couple of hours struggling with maven.
Unfortunately our hive environment can't update to 0.11.0 which support sql windowing.
Can you mail me(xkm2000@gmail.com) the jar file , or share the latest jar file in downloading area of this project. 

Thanks,
Rock

**Comment by hbutani** [comment]
This functionality is now available in hive 0.11

regards,
Harish.
