### ISSUE TITLE
Support for non-default db

### ISSUE THREAD

**Issue by kchatterjee** [hbutani/SQLWindowing#25]
I am trying to use a non-default db to issue the windowing queries. I see there is a patch for that but encountered some issue in building it. Can you send me (kasturi.chatterjee at gmail.com) a latest jar with the fix?

Thanks

**Comment by kchatterjee** [comment]
An Update: I was able to build the recent jar. But when I try to invoke the service, I get the following error:

hive --service windowingCli
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hive/common/io/CachingPrintStream
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:201)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hive.common.io.CachingPrintStream
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
