### ISSUE TITLE
where clause not working

### ISSUE THREAD

**Issue by achaubal** [hbutani/SQLWindowing#7]
Hey Harish,

I am running a query which has a final **where** clause

from <select    acct_no,to_date(mydt) my_date,
cv_tot_bal from mon_2011_08_all_attrib>
  partition    by  acct_no 
      order    by  acct_no, my_date asc
with  
RowNumber(cv_tot_bal) as  tot_rank,  Count(cv_tot_bal) as tot_count
select
acct_no, my_date, cv_tot_bal, tot_rank, tot_count
Where < tot_rank in ( tot_count/2 +1), (tot_count+1)/2) >
into path='ma_7_2011_08'

the query runs and the create table hive job compeltes successfully. But the next windowing Job never runs and there is no indication in the window as well, no error.
Without the *_where_ clause the query runs fine.

Is my **where** syntax ok?

i am trying to do a median.

ameet

**Comment by hbutani** [comment]
where clause needs to use groovy(which is superset of java) syntax:

<tot_rank \>= (tot_count/2 +1) && tot_rank <=  (tot_count+1)/2)  >

within the expression the '>' symbol has to be escaped

Did you download the new jars?

**Comment by achaubal** [comment]
yes, I did and can see the next stage now, thanks
but I am still getting the error parsing the where clause
**Failed to parse where Clause ' tot_rank = ( tot_count/2 +1)  ||  tot_rank =(tot_count+1)/2) '**

my query:
from <select    bc_prod_acct_no,to_date(bc_sys_sor_dt) bc_date,
cv_tot_bal from mon_2011_08_all_attrib>
  partition    by bc_prod_acct_no 
      order    by bc_prod_acct_no, bc_date asc
with  
RowNumber(cv_tot_bal) as  tot_rank,  Count(cv_tot_bal) as tot_count
select
bc_prod_acct_no, bc_date, cv_tot_bal, tot_rank, tot_count
Where < tot_rank = ( tot_count/2 +1)  ||  tot_rank =(tot_count+1)/2) >
into path='ma_7_2011_08';

**Comment by hbutani** [comment]
You have an extra ')' and you want == operator:

tot_rank == (tot_count/2 +1) || tot_rank == (tot_count+1)/2

**Comment by achaubal** [comment]
ok, that made the difference. However, now with that fixed and the new jar, I am getting a strange error in the final windowing stage - it goes upto 78% and complains that it can't create a directory. Not sure which one, since the final target directory is actually created. 

12/02/02 16:02:39 INFO mapred.JobClient:  map 100% reduce 77%
12/02/02 16:02:48 INFO mapred.JobClient:  map 100% reduce 78%
12/02/02 16:03:10 INFO mapred.JobClient: Task Id : attempt_201201151510_0195_r_000000_0, Status : FAILED
java.lang.IllegalStateException: Failed to create directory within 10000 attempts (tried 1328216567679-0 to 1328216567679-9999)
        at com.google.common.io.Files.createTempDir(Files.java:418)
        at com.sap.hadoop.ds.list.PartitionedByteBasedList.<init>(PartitionedByteBasedList.java:29)
        at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at com.sap.hadoop.windowing.runtime.Partition.<init>(Partition.groovy:42)
        at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
        at sun.reflect.Delegatin
attempt_201201151510_0195_r_000000_0: Query:
attempt_201201151510_0195_r_000000_0:   tableInput=(hiveTable=WindowingTempTable_1328216261599)
attempt_201201151510_0195_r_000000_0:   partitionColumns=bc_prod_acct_no
attempt_201201151510_0195_r_000000_0:   orderColumns=bc_prod_acct_no ASC, bc_date ASC
attempt_201201151510_0195_r_000000_0:   funcSpecs=[rownumber(alias=tot_rank, param=[id=cv_tot_bal], type=null, window=null),
attempt_201201151510_0195_r_000000_0:           count(alias=tot_count, param=[id=cv_tot_bal], type=null, window=null)]
attempt_201201151510_0195_r_000000_0:   select=bc_prod_acct_no, bc_date, cv_tot_bal, tot_rank, tot_count
attempt_201201151510_0195_r_000000_0:   whereExpr=tot_rank==(tot_count/2 +1)  ||  tot_rank==(tot_count+1)/2
attempt_201201151510_0195_r_000000_0:   tableOutput=(output(path=ma_7_2011_08, serde=org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, serDeProps={field.delim=,, columns=bc_prod_acct_no,bc_date,cv_tot_bal,tot_rank,tot_count, columns.types=bigint,string,float,int,int}, format=org.apache.hadoop.mapred.TextOutputFormat)
attempt_201201151510_0195_r_000000_0: log4j:WARN No appenders could be found for logger (org.apache.hadoop.hdfs.DFSClient).
attempt_201201151510_0195_r_000000_0: log4j:WARN Please initialize the log4j system properly.
12/02/02 16:03:11 INFO mapred.JobClient:  map 100% reduce 39%

Even in the logs inside HDFS under the target directory  ( which actually is getting created ) I see the error:
ReduceAttempt TASK_TYPE="REDUCE" TASKID="task_201201151510_0195_r_000001" TASK_ATTEMPT_ID="attempt_201201151510_0195_r_000001_0" TASK_STATUS="FAILED" FINISH_TIME="1328216593338" HOSTNAME="myhost8" ERROR="java.lang.IllegalStateException: Failed to create directory within 10000 attempts (tried 1328216572571-0 to 1328216572571-9999)
        at com.google.common.io.Files.createTempDir(Files.java:418)
        at com.sap.hadoop.ds.list.PartitionedByteBasedList.<init>(PartitionedByteBasedList.java:29)
        at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at com.sap.hadoop.windowing.runtime.Partition.<init>(Partition.groovy:42)
        at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
        at sun.reflect.Delegatin" .

thx

ameet

**Comment by hbutani** [comment]
The error has to do with the reduce task trying to create a Temp Directory on the tasknode. This is from another enhancement in this jar, to do with handling very large partitions, they will get spilled to disk. The key line in the stacktrace is this: 
at com.google.common.io.Files.createTempDir(Files.java:418)

Any clues on why creation of temp directories would fail in your cluster? 
Can you post the entire stacktrace from the job's log file.

**Comment by achaubal** [comment]
hmm, not sure, I checked the filesystem space and looks ok that node:
it's trying to create temporary files under /tmp ? that should be ok, or is it somewhere else.

in the logs, I see pretty much the same thing:

2012-02-02 16:01:07,420 INFO org.apache.hadoop.mapred.Merger: Down to the last merge-pass, with 1 segments left of total size: 35895341 bytes
2012-02-02 16:01:09,256 INFO hive.metastore: Trying to connect to metastore with URI thrift://bofa98:9083
2012-02-02 16:01:09,328 INFO hive.metastore: Connected to metastore.
2012-02-02 16:01:09,388 INFO hive.log: DDL: struct windowingtemptable_1328216261599 { i64 bc_prod_acct_no, string bc_date, float cv_tot_bal}
2012-02-02 16:02:52,783 INFO org.apache.hadoop.mapred.TaskLogsTruncater: Initializing logs' truncater with mapRetainSize=-1 and reduceRetainSize=-1
2012-02-02 16:02:52,786 WARN org.apache.hadoop.mapred.Child: Error running child
java.lang.IllegalStateException: Failed to create directory within 10000 attempts (tried 1328216572571-0 to 1328216572571-9999)
        at com.google.common.io.Files.createTempDir(Files.java:418)
        at com.sap.hadoop.ds.list.PartitionedByteBasedList.<init>(PartitionedByteBasedList.java:29)
        at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at com.sap.hadoop.windowing.runtime.Partition.<init>(Partition.groovy:42)
        at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at com.sap.hadoop.windowing.runtime.mr.Reduce.reduce(Reduce.groovy:83)
        at com.sap.hadoop.windowing.runtime.mr.Reduce.reduce(Reduce.groovy)
        at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:469)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:417)
        at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:396)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)

**Comment by achaubal** [comment]
this is the only reference I found to the error: http://team.ops4j.org/browse/PAXEXAM-294 which suggests that it's looking for existence of the directory rather than trying to create it.. does it make sense?

**Comment by hbutani** [comment]
it is trying to create a directory under the directory set by 'java.io.tmpdir' which by default is /tmp.
can you check the permissions on the tmp directory. 
Also try manually doing a mkdir on a tasknode.

**Comment by achaubal** [comment]
yes, already did. I can do a mkdir on /tmp as any user . standard perm with sticky bit. could it be trying it under somewhere else?
Also, I tried this on the node that was shown in the error logs as well as the node running the hive client. However, it should be the same as part of standard Unix procedure which I haven't meddled with .

**Comment by hbutani** [comment]
1. check your clusters hadoop and hive env files to see if java.io.tmpdir has been overidden
2. to explicitly set the tmp dir you will have to add something like this to the hadoop env:
   export HADOOP_OPTS="$HADOOP_OPTS -Djava.io.tmpdir=/tmp'
   this will have to done for all tasknodes.

**Comment by achaubal** [comment]
actually, now all the queries are breaking, even without the **where** clause. I know that I haven't changed anything to do with io.tmpdir and don't really see a reason why that would be changed. I will try to confirm what the value of that variable is to see if it reports something different from /tmp

**Comment by hbutani** [comment]
yes all queries will fail. I'm going to make the handling of large partitions configurable so we can get around this issue

**Comment by achaubal** [comment]
ok, just tried this to confirm the temp dir :

public class TempDir {
  public static void main(String[] args) {
    String tmpDir = System.getProperty("java.io.tmpdir");
    System.out.println("java.io.tmpdir: [" + tmpDir + "]");
  }
}

and it prints: java.io.tmpdir: [/tmp]
 on all the nodes. 

So it is /tmp and I can confirm that a user can write to that dir. It's got the standard sticky bit set
drwxrwxrwt  8 root root  4096 Feb  2 17:01 /tmp

thx

ameet

**Comment by hbutani** [comment]
thanks for checking. Let me think about this one.

In the meantime can you downloaded a new set of jars. Now the internal Partition class is configurable and the mem size is also. By default it uses an in-memory partition class and allocates 16MB. So you should not hit the createTempDir error.
To change the partition size set
com.sap.hadoop.windowing.partition.memory.size = to a value in bytes
Once we figure out the createTempDir issue you can change the partition class, set:
com.sap.hadoop.windowing.partition.class = om.sap.hadoop.ds.list.PartitionedByteBasedList

See com.sap.hadoop.windowing.runtime.LargePartitionTest for a eg on setting these parameters.

**Comment by hbutani** [comment]
Can you try this:

import com.google.common.io.Files;

public class TempDir
{
    public static void main(String[] args)
    {
        String tmpDir = System.getProperty("java.io.tmpdir");
        System.out.println("java.io.tmpdir: [" + tmpDir + "]");
        System.out.println(Files.createTempDir());
    }
}

run as 
java -classpath .../com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar TempDir
does it create a directory under /tmp

**Comment by achaubal** [comment]
yep it did:

 javac -classpath /tmp/windowing/com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar TempDir.java 

 java -classpath /tmp/windowing/com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar:. TempDir

output:
java.io.tmpdir: [/tmp]
/tmp/1328234107269-0

verification:
 ls /tmp/
1328234107269-0  hadoop-ameet      hsperfdata_hdfs    hsperfdata_root
ameet            hsperfdata_ameet  hsperfdata_mapred  windowing
[ameet@myhost ~]$ ls /tmp/1328234107269-0/
[ameet@myhost ~]$ ls -l /tmp/1328234107269-0/

**Comment by achaubal** [comment]
btw, the new jar worked fine. without any options. and I can run the median query with the **where** clause .

thx much 

ameet

**Comment by achaubal** [comment]
so what's the impact of this change? am I limited to the amount of data that can be safely processed? because you are not spilling to disk ?

**Comment by hbutani** [comment]
The size applies to each partition, not to to the entire dataset. Also you can assign more space with the 'com.sap.hadoop.windowing.partition.memory.size' option. Should be ok in most situations. But for very very large partitions you will run OutOfMemory.
I had switched to the Persistent partitions by default, w/o allowing the user any choice. I think this is a better strategy allowing users to trade memory for performance. 
But still need to find the reason for the createTempDir errorr....

**Comment by achaubal** [comment]
ok makes sense, can you elaborate how exactly to change the size,
you mentioned:
  change the partition size set
_com.sap.hadoop.windowing.partition.memory.size = to a value in bytes
Once we figure out the createTempDir issue you can change the partition class, set:
com.sap.hadoop.windowing.partition.class = om.sap.hadoop.ds.list.PartitionedByteBasedList
See com.sap.hadoop.windowing.runtime.LargePartitionTest for a eg on setting these parameters._

can you explain where and how exactly to do this?

thanks

ameet

**Comment by hbutani** [comment]
in your hive-site.xml just add these properties.

**Comment by hbutani** [comment]
Closing this issue and opening a new one to reflect issue with Persistent Partitions
